### PR TITLE
Use browserslist to generate rem fallbacks only when needed

### PR DESCRIPTION
**Pull request by iamvdo**

### CODE REVIEW

**Comment by MoOx** [comment]
This looks good !

**Comment by iamvdo** [comment]
Quick question: is this change a break or a feature?
For me it's a feature, but as it generates a different output, is it considered a break? I'm always a bit confused with that.

**Comment by MoOx** [comment]
Since you forced default `browsers` value to act like it was, it's not a breaking change.
Otherwise you will had to change some tests ;)
It's a new feature that keep the default (current) behavior, so looks like a minor change to me.

That said, we can imagine a major bump (breaking change) where you remove the default value of `browsers` and rely on default browserlist option. browserslist is looking for file or env var so it would be nice to let this plugin use it if possible (see readme https://github.com/ai/browserslist).

**Comment by iamvdo** [comment]
OK, I stay here for now. Open issues for the rest. ;)

**Pull request merged**
